version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: sistema-gestao-db
    environment:
      POSTGRES_DB: InfoDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: RF@DB##&441
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database-setup.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sistema-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  sistema-gestao:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistema-gestao-app
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=InfoDB
      - DB_USER=postgres
      - DB_PASSWORD=RF@DB##&441
      - JWT_SECRET=your-jwt-secret-key-here-change-this-in-production
      - DOMAIN=https://your-domain.com
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sistema-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  sistema-network:
    driver: bridge
    name: sistema-gestao-network

volumes:
  postgres_data:
    driver: local